apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ree-ai

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - api-gateway.yaml

commonLabels:
  app.kubernetes.io/name: ree-ai
  app.kubernetes.io/part-of: ree-ai-platform
